// Generated by rstantools.  Do not edit by hand.

/*
    cityHeatHealth is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    cityHeatHealth is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with cityHeatHealth.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_SB_CondPoisson_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 102> locations_array__ =
  {" (found before start of program)",
  " (in 'SB_CondPoisson', line 56, column 2 to column 15)",
  " (in 'SB_CondPoisson', line 57, column 2 to column 27)",
  " (in 'SB_CondPoisson', line 59, column 2 to column 26)",
  " (in 'SB_CondPoisson', line 61, column 2 to column 25)",
  " (in 'SB_CondPoisson', line 159, column 2 to column 24)",
  " (in 'SB_CondPoisson', line 162, column 6 to column 45)",
  " (in 'SB_CondPoisson', line 161, column 18 to line 163, column 5)",
  " (in 'SB_CondPoisson', line 161, column 4 to line 163, column 5)",
  " (in 'SB_CondPoisson', line 160, column 16 to line 164, column 3)",
  " (in 'SB_CondPoisson', line 160, column 2 to line 164, column 3)",
  " (in 'SB_CondPoisson', line 67, column 2 to column 20)",
  " (in 'SB_CondPoisson', line 68, column 2 to column 19)",
  " (in 'SB_CondPoisson', line 69, column 2 to column 23)",
  " (in 'SB_CondPoisson', line 89, column 9 to column 10)",
  " (in 'SB_CondPoisson', line 89, column 12 to column 13)",
  " (in 'SB_CondPoisson', line 89, column 2 to column 48)",
  " (in 'SB_CondPoisson', line 92, column 13 to column 14)",
  " (in 'SB_CondPoisson', line 92, column 2 to column 50)",
  " (in 'SB_CondPoisson', line 98, column 9 to column 10)",
  " (in 'SB_CondPoisson', line 98, column 11 to column 12)",
  " (in 'SB_CondPoisson', line 98, column 2 to column 79)",
  " (in 'SB_CondPoisson', line 102, column 9 to column 10)",
  " (in 'SB_CondPoisson', line 102, column 12 to column 13)",
  " (in 'SB_CondPoisson', line 102, column 2 to column 86)",
  " (in 'SB_CondPoisson', line 104, column 2 to column 74)",
  " (in 'SB_CondPoisson', line 110, column 9 to column 10)",
  " (in 'SB_CondPoisson', line 110, column 12 to column 13)",
  " (in 'SB_CondPoisson', line 110, column 2 to column 52)",
  " (in 'SB_CondPoisson', line 115, column 9 to column 10)",
  " (in 'SB_CondPoisson', line 115, column 12 to column 13)",
  " (in 'SB_CondPoisson', line 115, column 2 to column 21)",
  " (in 'SB_CondPoisson', line 124, column 4 to column 50)",
  " (in 'SB_CondPoisson', line 116, column 16 to line 125, column 3)",
  " (in 'SB_CondPoisson', line 116, column 2 to line 125, column 3)",
  " (in 'SB_CondPoisson', line 128, column 9 to column 10)",
  " (in 'SB_CondPoisson', line 128, column 12 to column 13)",
  " (in 'SB_CondPoisson', line 128, column 2 to column 45)",
  " (in 'SB_CondPoisson', line 131, column 9 to column 10)",
  " (in 'SB_CondPoisson', line 131, column 12 to column 13)",
  " (in 'SB_CondPoisson', line 131, column 2 to column 50)",
  " (in 'SB_CondPoisson', line 140, column 10 to column 23)",
  " (in 'SB_CondPoisson', line 140, column 4 to column 72)",
  " (in 'SB_CondPoisson', line 151, column 10 to column 74)",
  " (in 'SB_CondPoisson', line 149, column 16 to line 152, column 10)",
  " (in 'SB_CondPoisson', line 144, column 45 to line 149, column 10)",
  " (in 'SB_CondPoisson', line 144, column 9 to line 152, column 10)",
  " (in 'SB_CondPoisson', line 143, column 35 to line 153, column 8)",
  " (in 'SB_CondPoisson', line 143, column 7 to line 153, column 8)",
  " (in 'SB_CondPoisson', line 141, column 18 to line 154, column 5)",
  " (in 'SB_CondPoisson', line 141, column 4 to line 154, column 5)",
  " (in 'SB_CondPoisson', line 136, column 24 to line 155, column 3)",
  " (in 'SB_CondPoisson', line 136, column 2 to line 155, column 3)",
  " (in 'SB_CondPoisson', line 3, column 2 to column 17)",
  " (in 'SB_CondPoisson', line 4, column 9 to column 10)",
  " (in 'SB_CondPoisson', line 4, column 12 to column 13)",
  " (in 'SB_CondPoisson', line 4, column 2 to column 20)",
  " (in 'SB_CondPoisson', line 6, column 2 to column 17)",
  " (in 'SB_CondPoisson', line 7, column 2 to column 17)",
  " (in 'SB_CondPoisson', line 8, column 8 to column 9)",
  " (in 'SB_CondPoisson', line 8, column 11 to column 12)",
  " (in 'SB_CondPoisson', line 8, column 14 to column 15)",
  " (in 'SB_CondPoisson', line 8, column 2 to column 24)",
  " (in 'SB_CondPoisson', line 9, column 8 to column 9)",
  " (in 'SB_CondPoisson', line 9, column 11 to column 12)",
  " (in 'SB_CondPoisson', line 9, column 2 to column 29)",
  " (in 'SB_CondPoisson', line 14, column 9 to column 10)",
  " (in 'SB_CondPoisson', line 14, column 12 to column 13)",
  " (in 'SB_CondPoisson', line 14, column 2 to column 17)",
  " (in 'SB_CondPoisson', line 15, column 2 to column 24)",
  " (in 'SB_CondPoisson', line 16, column 2 to column 29)",
  " (in 'SB_CondPoisson', line 17, column 8 to column 16)",
  " (in 'SB_CondPoisson', line 17, column 18 to column 31)",
  " (in 'SB_CondPoisson', line 17, column 2 to column 49)",
  " (in 'SB_CondPoisson', line 18, column 8 to column 9)",
  " (in 'SB_CondPoisson', line 18, column 2 to column 35)",
  " (in 'SB_CondPoisson', line 27, column 13 to column 14)",
  " (in 'SB_CondPoisson', line 27, column 2 to column 20)",
  " (in 'SB_CondPoisson', line 29, column 4 to column 28)",
  " (in 'SB_CondPoisson', line 28, column 16 to line 30, column 3)",
  " (in 'SB_CondPoisson', line 28, column 2 to line 30, column 3)",
  " (in 'SB_CondPoisson', line 39, column 8 to column 16)",
  " (in 'SB_CondPoisson', line 39, column 2 to column 33)",
  " (in 'SB_CondPoisson', line 41, column 7 to column 26)",
  " (in 'SB_CondPoisson', line 43, column 35 to column 51)",
  " (in 'SB_CondPoisson', line 43, column 9 to column 51)",
  " (in 'SB_CondPoisson', line 42, column 33 to line 44, column 8)",
  " (in 'SB_CondPoisson', line 42, column 7 to line 44, column 8)",
  " (in 'SB_CondPoisson', line 45, column 6 to column 33)",
  " (in 'SB_CondPoisson', line 40, column 23 to line 46, column 3)",
  " (in 'SB_CondPoisson', line 40, column 2 to line 46, column 3)",
  " (in 'SB_CondPoisson', line 48, column 8 to column 16)",
  " (in 'SB_CondPoisson', line 48, column 2 to column 28)",
  " (in 'SB_CondPoisson', line 50, column 4 to column 17)",
  " (in 'SB_CondPoisson', line 49, column 23 to line 51, column 3)",
  " (in 'SB_CondPoisson', line 49, column 2 to line 51, column 3)",
  " (in 'SB_CondPoisson', line 56, column 9 to column 10)",
  " (in 'SB_CondPoisson', line 57, column 18 to column 19)",
  " (in 'SB_CondPoisson', line 61, column 9 to column 10)",
  " (in 'SB_CondPoisson', line 61, column 12 to column 13)",
  " (in 'SB_CondPoisson', line 159, column 9 to column 10)",
  " (in 'SB_CondPoisson', line 159, column 12 to column 13)"};
#include <stan_meta_header.hpp>
class model_SB_CondPoisson final : public model_base_crtp<model_SB_CondPoisson> {
private:
  int J;
  Eigen::Matrix<double,-1,-1> Jmat_data__;
  int N;
  int K;
  std::vector<std::vector<std::vector<double>>> X;
  std::vector<std::vector<int>> y;
  Eigen::Matrix<double,-1,-1> S_data__;
  int n_strata;
  int max_in_strata;
  std::vector<std::vector<int>> S_condensed;
  std::vector<int> stratum_id;
  Eigen::Matrix<double,1,-1> n_a_data__;
  std::vector<int> strata_len;
  std::vector<int> dummy;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Jmat{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> S{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,1,-1>> n_a{nullptr, 0};
public:
  ~model_SB_CondPoisson() {}
  model_SB_CondPoisson(stan::io::var_context& context__, unsigned int
                       random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_SB_CondPoisson_namespace::model_SB_CondPoisson";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 53;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 53;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 53;
      stan::math::check_greater_or_equal(function__, "J", J, 1);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("Jmat", "J", J);
      current_statement__ = 55;
      stan::math::validate_non_negative_index("Jmat", "J", J);
      current_statement__ = 56;
      context__.validate_dims("data initialization", "Jmat", "double",
        std::vector<size_t>{static_cast<size_t>(J), static_cast<size_t>(J)});
      Jmat_data__ = Eigen::Matrix<double,-1,-1>::Constant(J, J,
                      std::numeric_limits<double>::quiet_NaN());
      new (&Jmat) Eigen::Map<Eigen::Matrix<double,-1,-1>>(Jmat_data__.data(),
        J, J);
      {
        std::vector<local_scalar_t__> Jmat_flat__;
        current_statement__ = 56;
        Jmat_flat__ = context__.vals_r("Jmat");
        current_statement__ = 56;
        pos__ = 1;
        current_statement__ = 56;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 56;
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            current_statement__ = 56;
            stan::model::assign(Jmat, Jmat_flat__[(pos__ - 1)],
              "assigning variable Jmat", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 56;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 57;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 57;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 57;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 58;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 58;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 58;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("X", "K", K);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("X", "J", J);
      current_statement__ = 62;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K),
          static_cast<size_t>(J)});
      X = std::vector<std::vector<std::vector<double>>>(N,
            std::vector<std::vector<double>>(K,
              std::vector<double>(J,
                std::numeric_limits<double>::quiet_NaN())));
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 62;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 62;
        pos__ = 1;
        current_statement__ = 62;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 62;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 62;
            for (int sym3__ = 1; sym3__ <= N; ++sym3__) {
              current_statement__ = 62;
              stan::model::assign(X, X_flat__[(pos__ - 1)],
                "assigning variable X", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 62;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 63;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("y", "J", J);
      current_statement__ = 65;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(J)});
      y = std::vector<std::vector<int>>(N,
            std::vector<int>(J, std::numeric_limits<int>::min()));
      {
        std::vector<int> y_flat__;
        current_statement__ = 65;
        y_flat__ = context__.vals_i("y");
        current_statement__ = 65;
        pos__ = 1;
        current_statement__ = 65;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 65;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 65;
            stan::model::assign(y, y_flat__[(pos__ - 1)],
              "assigning variable y", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 65;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 65;
      stan::math::check_greater_or_equal(function__, "y", y, 0);
      current_statement__ = 66;
      stan::math::validate_non_negative_index("S", "N", N);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("S", "N", N);
      current_statement__ = 68;
      context__.validate_dims("data initialization", "S", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(N)});
      S_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&S) Eigen::Map<Eigen::Matrix<double,-1,-1>>(S_data__.data(), N, N);
      {
        std::vector<local_scalar_t__> S_flat__;
        current_statement__ = 68;
        S_flat__ = context__.vals_r("S");
        current_statement__ = 68;
        pos__ = 1;
        current_statement__ = 68;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 68;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 68;
            stan::model::assign(S, S_flat__[(pos__ - 1)],
              "assigning variable S", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 68;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 69;
      context__.validate_dims("data initialization", "n_strata", "int",
        std::vector<size_t>{});
      n_strata = std::numeric_limits<int>::min();
      current_statement__ = 69;
      n_strata = context__.vals_i("n_strata")[(1 - 1)];
      current_statement__ = 69;
      stan::math::check_greater_or_equal(function__, "n_strata", n_strata, 1);
      current_statement__ = 70;
      context__.validate_dims("data initialization", "max_in_strata", "int",
        std::vector<size_t>{});
      max_in_strata = std::numeric_limits<int>::min();
      current_statement__ = 70;
      max_in_strata = context__.vals_i("max_in_strata")[(1 - 1)];
      current_statement__ = 70;
      stan::math::check_greater_or_equal(function__, "max_in_strata",
        max_in_strata, 1);
      current_statement__ = 71;
      stan::math::validate_non_negative_index("S_condensed", "n_strata",
        n_strata);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("S_condensed", "max_in_strata",
        max_in_strata);
      current_statement__ = 73;
      context__.validate_dims("data initialization", "S_condensed", "int",
        std::vector<size_t>{static_cast<size_t>(n_strata),
          static_cast<size_t>(max_in_strata)});
      S_condensed = std::vector<std::vector<int>>(n_strata,
                      std::vector<int>(max_in_strata,
                        std::numeric_limits<int>::min()));
      {
        std::vector<int> S_condensed_flat__;
        current_statement__ = 73;
        S_condensed_flat__ = context__.vals_i("S_condensed");
        current_statement__ = 73;
        pos__ = 1;
        current_statement__ = 73;
        for (int sym1__ = 1; sym1__ <= max_in_strata; ++sym1__) {
          current_statement__ = 73;
          for (int sym2__ = 1; sym2__ <= n_strata; ++sym2__) {
            current_statement__ = 73;
            stan::model::assign(S_condensed, S_condensed_flat__[(pos__ - 1)],
              "assigning variable S_condensed",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 73;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 74;
      stan::math::validate_non_negative_index("stratum_id", "N", N);
      current_statement__ = 75;
      context__.validate_dims("data initialization", "stratum_id", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      stratum_id = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 75;
      stratum_id = context__.vals_i("stratum_id");
      current_statement__ = 75;
      stan::math::check_greater_or_equal(function__, "stratum_id",
        stratum_id, 0);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("n_a", "J", J);
      current_statement__ = 77;
      n_a_data__ = Eigen::Matrix<double,1,-1>::Constant(J,
                     std::numeric_limits<double>::quiet_NaN());
      new (&n_a) Eigen::Map<Eigen::Matrix<double,1,-1>>(n_a_data__.data(), J);
      current_statement__ = 80;
      for (int j = 1; j <= J; ++j) {
        current_statement__ = 78;
        stan::model::assign(n_a,
          stan::math::sum(
            stan::model::rvalue(Jmat, "Jmat", stan::model::index_uni(j),
              stan::model::index_omni())), "assigning variable n_a",
          stan::model::index_uni(j));
      }
      current_statement__ = 81;
      stan::math::validate_non_negative_index("strata_len", "n_strata",
        n_strata);
      current_statement__ = 82;
      strata_len = std::vector<int>(n_strata,
                     std::numeric_limits<int>::min());
      current_statement__ = 90;
      for (int n = 1; n <= n_strata; ++n) {
        int k_not_zero = std::numeric_limits<int>::min();
        current_statement__ = 83;
        k_not_zero = 0;
        current_statement__ = 87;
        for (int k = 1; k <= max_in_strata; ++k) {
          current_statement__ = 85;
          if (stan::math::logical_gt(
                stan::model::rvalue(S_condensed, "S_condensed",
                  stan::model::index_uni(n), stan::model::index_uni(k)), 0)) {
            current_statement__ = 84;
            k_not_zero = (k_not_zero + 1);
          }
        }
        current_statement__ = 88;
        stan::model::assign(strata_len, k_not_zero,
          "assigning variable strata_len", stan::model::index_uni(n));
      }
      current_statement__ = 91;
      stan::math::validate_non_negative_index("dummy", "n_strata", n_strata);
      current_statement__ = 92;
      dummy = std::vector<int>(n_strata, std::numeric_limits<int>::min());
      current_statement__ = 95;
      for (int n = 1; n <= n_strata; ++n) {
        current_statement__ = 93;
        stan::model::assign(dummy, n, "assigning variable dummy",
          stan::model::index_uni(n));
      }
      current_statement__ = 96;
      stan::math::validate_non_negative_index("mu", "K", K);
      current_statement__ = 97;
      stan::math::validate_non_negative_index("sigma", "K", K);
      current_statement__ = 98;
      stan::math::validate_non_negative_index("beta_star", "K", K);
      current_statement__ = 99;
      stan::math::validate_non_negative_index("beta_star", "J", J);
      current_statement__ = 100;
      stan::math::validate_non_negative_index("beta_out", "K", K);
      current_statement__ = 101;
      stan::math::validate_non_negative_index("beta_out", "J", J);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = K + K + 1 + (K * J);
  }
  inline std::string model_name() const final {
    return "model_SB_CondPoisson";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_SB_CondPoisson_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      mu = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 2;
      sigma = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, K);
      local_scalar_t__ q = DUMMY_VAR__;
      current_statement__ = 3;
      q = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
            1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_star =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, J, DUMMY_VAR__);
      current_statement__ = 4;
      beta_star = in__.template read<
                    Eigen::Matrix<local_scalar_t__,-1,-1>>(K, J);
      {
        current_statement__ = 11;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(mu));
        current_statement__ = 12;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(q));
        current_statement__ = 13;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(sigma));
        current_statement__ = 14;
        stan::math::validate_non_negative_index("beta_star_sum", "K", K);
        current_statement__ = 15;
        stan::math::validate_non_negative_index("beta_star_sum", "J", J);
        Eigen::Matrix<local_scalar_t__,-1,-1> beta_star_sum =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, J, DUMMY_VAR__);
        current_statement__ = 16;
        stan::model::assign(beta_star_sum,
          stan::math::multiply(beta_star, Jmat),
          "assigning variable beta_star_sum");
        current_statement__ = 17;
        stan::math::validate_non_negative_index("beta_star_denom", "J", J);
        Eigen::Matrix<local_scalar_t__,1,-1> beta_star_denom =
          Eigen::Matrix<local_scalar_t__,1,-1>::Constant(J, DUMMY_VAR__);
        current_statement__ = 18;
        stan::model::assign(beta_star_denom,
          stan::math::add((1 - q), stan::math::multiply(q, n_a)),
          "assigning variable beta_star_denom");
        current_statement__ = 19;
        stan::math::validate_non_negative_index("star_mean", "K", K);
        current_statement__ = 20;
        stan::math::validate_non_negative_index("star_mean", "J", J);
        Eigen::Matrix<local_scalar_t__,-1,-1> star_mean =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, J, DUMMY_VAR__);
        current_statement__ = 21;
        stan::model::assign(star_mean,
          stan::math::elt_multiply(
            stan::math::rep_matrix(
              stan::math::elt_divide(q, beta_star_denom), K), beta_star_sum),
          "assigning variable star_mean");
        current_statement__ = 22;
        stan::math::validate_non_negative_index("star_sd", "K", K);
        current_statement__ = 23;
        stan::math::validate_non_negative_index("star_sd", "J", J);
        Eigen::Matrix<local_scalar_t__,-1,-1> star_sd =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, J, DUMMY_VAR__);
        current_statement__ = 24;
        stan::model::assign(star_sd,
          stan::math::elt_divide(stan::math::rep_matrix(sigma, J),
            stan::math::rep_matrix(stan::math::sqrt(beta_star_denom), K)),
          "assigning variable star_sd");
        current_statement__ = 25;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         stan::math::to_vector(beta_star),
                         stan::math::to_vector(star_mean),
                         stan::math::to_vector(star_sd)));
        current_statement__ = 26;
        stan::math::validate_non_negative_index("beta", "K", K);
        current_statement__ = 27;
        stan::math::validate_non_negative_index("beta", "J", J);
        Eigen::Matrix<local_scalar_t__,-1,-1> beta =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, J, DUMMY_VAR__);
        current_statement__ = 28;
        stan::model::assign(beta,
          stan::math::add(stan::math::rep_matrix(mu, J), beta_star),
          "assigning variable beta");
        current_statement__ = 29;
        stan::math::validate_non_negative_index("xBeta", "N", N);
        current_statement__ = 30;
        stan::math::validate_non_negative_index("xBeta", "J", J);
        Eigen::Matrix<local_scalar_t__,-1,-1> xBeta =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, J, DUMMY_VAR__);
        current_statement__ = 34;
        for (int j = 1; j <= J; ++j) {
          current_statement__ = 32;
          stan::model::assign(xBeta,
            stan::math::exp(
              stan::math::multiply(
                stan::math::to_matrix(
                  stan::model::rvalue(X, "X", stan::model::index_omni(),
                    stan::model::index_omni(), stan::model::index_uni(j))),
                stan::model::rvalue(beta, "beta", stan::model::index_omni(),
                  stan::model::index_uni(j)))), "assigning variable xBeta",
            stan::model::index_omni(), stan::model::index_uni(j));
        }
        current_statement__ = 35;
        stan::math::validate_non_negative_index("theta_denominator", "N", N);
        current_statement__ = 36;
        stan::math::validate_non_negative_index("theta_denominator", "J", J);
        Eigen::Matrix<local_scalar_t__,-1,-1> theta_denominator =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, J, DUMMY_VAR__);
        current_statement__ = 37;
        stan::model::assign(theta_denominator,
          stan::math::multiply(S, xBeta),
          "assigning variable theta_denominator");
        current_statement__ = 38;
        stan::math::validate_non_negative_index("theta", "N", N);
        current_statement__ = 39;
        stan::math::validate_non_negative_index("theta", "J", J);
        Eigen::Matrix<local_scalar_t__,-1,-1> theta =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, J, DUMMY_VAR__);
        current_statement__ = 40;
        stan::model::assign(theta,
          stan::math::elt_divide(xBeta, theta_denominator),
          "assigning variable theta");
        current_statement__ = 52;
        for (int i = 1; i <= n_strata; ++i) {
          current_statement__ = 41;
          stan::math::validate_non_negative_index("my_array",
            "strata_len[i]",
            stan::model::rvalue(strata_len, "strata_len",
              stan::model::index_uni(i)));
          std::vector<int> my_array =
            std::vector<int>(stan::model::rvalue(strata_len, "strata_len",
                               stan::model::index_uni(i)),
              std::numeric_limits<int>::min());
          current_statement__ = 42;
          stan::model::assign(my_array,
            stan::model::rvalue(S_condensed, "S_condensed",
              stan::model::index_uni(i),
              stan::model::index_min_max(1,
                stan::model::rvalue(strata_len, "strata_len",
                  stan::model::index_uni(i)))), "assigning variable my_array");
          current_statement__ = 50;
          for (int j = 1; j <= J; ++j) {
            current_statement__ = 48;
            if (stan::math::logical_gt(
                  stan::math::sum(
                    stan::model::rvalue(y, "y",
                      stan::model::index_multi(my_array),
                      stan::model::index_uni(j))), 0)) {
              current_statement__ = 46;
              if (stan::math::is_nan(
                    stan::math::sum(
                      stan::model::rvalue(theta, "theta",
                        stan::model::index_multi(my_array),
                        stan::model::index_uni(j))))) {} else {
                                                         current_statement__ = 43;
                                                         lp_accum__.add(
                                                           stan::math::multinomial_lpmf<
                                                             false>(
                                                             stan::model::rvalue(
                                                               y, "y",
                                                               stan::model::index_multi(
                                                                 my_array),
                                                               stan::model::index_uni(
                                                                 j)),
                                                             stan::model::rvalue(
                                                               theta,
                                                               "theta",
                                                               stan::model::index_multi(
                                                                 my_array),
                                                               stan::model::index_uni(
                                                                 j))));
              }
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_SB_CondPoisson_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> mu =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      mu = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<double,-1,1> sigma =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      sigma = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, K);
      double q = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      q = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
            1, lp__);
      Eigen::Matrix<double,-1,-1> beta_star =
        Eigen::Matrix<double,-1,-1>::Constant(K, J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      beta_star = in__.template read<
                    Eigen::Matrix<local_scalar_t__,-1,-1>>(K, J);
      out__.write(mu);
      out__.write(sigma);
      out__.write(q);
      out__.write(beta_star);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,-1> beta_out =
        Eigen::Matrix<double,-1,-1>::Constant(K, J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 10;
      for (int k = 1; k <= K; ++k) {
        current_statement__ = 8;
        for (int j = 1; j <= J; ++j) {
          current_statement__ = 6;
          stan::model::assign(beta_out,
            (stan::model::rvalue(mu, "mu", stan::model::index_uni(k)) +
            stan::model::rvalue(beta_star, "beta_star",
              stan::model::index_uni(k), stan::model::index_uni(j))),
            "assigning variable beta_out", stan::model::index_uni(k),
            stan::model::index_uni(j));
        }
      }
      out__.write(beta_out);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(mu,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable mu");
      out__.write(mu);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(sigma,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable sigma");
      out__.write_free_lb(0, sigma);
      local_scalar_t__ q = DUMMY_VAR__;
      current_statement__ = 3;
      q = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, q);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_star =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, J, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(beta_star,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(K, J),
        "assigning variable beta_star");
      out__.write(beta_star);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "q", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "beta_star",
        "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(J)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> mu_flat__;
        current_statement__ = 1;
        mu_flat__ = context__.vals_r("mu");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(mu, mu_flat__[(pos__ - 1)],
            "assigning variable mu", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(mu);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sigma_flat__;
        current_statement__ = 2;
        sigma_flat__ = context__.vals_r("sigma");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(sigma, sigma_flat__[(pos__ - 1)],
            "assigning variable sigma", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sigma);
      local_scalar_t__ q = DUMMY_VAR__;
      current_statement__ = 3;
      q = context__.vals_r("q")[(1 - 1)];
      out__.write_free_lub(0, 1, q);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_star =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_star_flat__;
        current_statement__ = 4;
        beta_star_flat__ = context__.vals_r("beta_star");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 4;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 4;
            stan::model::assign(beta_star, beta_star_flat__[(pos__ - 1)],
              "assigning variable beta_star", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 4;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(beta_star);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mu", "sigma", "q", "beta_star"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"beta_out"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(K)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(K),
                  static_cast<size_t>(J)}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(K),
               static_cast<size_t>(J)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "q");
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta_star" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          param_names__.emplace_back(std::string() + "beta_out" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "q");
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta_star" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          param_names__.emplace_back(std::string() + "beta_out" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"q\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_star\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"beta_out\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(J) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"q\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_star\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"beta_out\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(J) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((K + K) + 1) + (K * J));
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * ((K * J));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((K + K) + 1) + (K * J));
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * ((K * J));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_SB_CondPoisson_namespace::model_SB_CondPoisson;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_SB_CondPoisson_namespace::profiles__;
}
#endif
#endif
